# Dependencies

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Supuesto
tagline:          'Prueba de sitio'
description:      'Acá iría una breve descripción del sitio'
url:              
baseurl:          "/"

author:
  name:           'Supuesto'
  url:            

paginate:         5

# Custom vars
version:          2.1.0



plugins:
  - jekyll-paginate
  - jekyll-gist
